name: Deploy SvelteKit to GitHub Pages

on:
  # Trigger deployment on push to the main branch
  push:
    branches:
      - main

  # Allow for manual deployment
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project for static export
      - name: Build the SvelteKit project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
