name: Deploy SvelteKit to GitHub Pages

on:
  # Deploy on push to main
  push:
    branches: [main]

  # Allow manual deployment
  workflow_dispatch:

# Grant GITHUB_TOKEN permissions needed for deployment to Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: sveltekit

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build

    # Deploy to github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
      - uses: actions/deploy-pages@v4
